'use client';

import Link from 'next/link';

export default function DisclaimerPage() {
  return (
    <div className="page-container animate-fade-in">
      <div className="card" style={{ maxWidth: '800px', margin: '0 auto', padding: '40px' }}>
        <h1 className="game-title" style={{ textAlign: 'left', fontSize: '36px', marginBottom: '24px' }}>
          <span style={{ color: '#ffe600' }}>Disclaimer</span>
        </h1>
        
        <div style={{ color: '#ccc', lineHeight: '1.6', fontSize: '14px' }}>
          <p style={{ marginBottom: '20px' }}>
            Last Updated: March 20, 2026
          </p>

          <h2 style={{ color: '#fff', fontSize: '20px', marginTop: '32px', marginBottom: '16px' }}>General Disclaimer</h2>
          <p>
            The information provided on VIBEMENOW (<strong>vibemenow.uk</strong>) is for general entertainment and informational purposes only. All games, quizzes, personality assessments, and articles on this website are intended purely for fun and should not be taken as professional advice of any kind—including but not limited to psychological, medical, educational, or financial advice.
          </p>

          <h2 style={{ color: '#fff', fontSize: '20px', marginTop: '32px', marginBottom: '16px' }}>Personality Quiz Results & Game Outcomes</h2>
          <p>
            The results generated by our personality quizzes (such as "Vibe Quiz") and other assessment-style games are created for entertainment purposes. They are not scientifically validated psychological instruments. The results do not constitute a clinical diagnosis, a personality assessment, or any form of professional evaluation. You should not make life decisions based on the outcomes of our games.
          </p>

          <h2 style={{ color: '#fff', fontSize: '20px', marginTop: '32px', marginBottom: '16px' }}>Accuracy of Information</h2>
          <p>
            While we strive to keep the information on VIBEMENOW accurate and up-to-date (including trivia questions, geographical data, and guide articles), we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or availability of the information, products, services, or related graphics contained on the website. Any reliance you place on such information is at your own risk.
          </p>

          <h2 style={{ color: '#fff', fontSize: '20px', marginTop: '32px', marginBottom: '16px' }}>External Links Disclaimer</h2>
          <p>
            VIBEMENOW may contain links to external websites that are not provided or maintained by us. Please note that we do not guarantee the accuracy, relevance, timeliness, or completeness of any information on these external websites. The inclusion of any links does not necessarily imply a recommendation or endorsement of the views expressed within them.
          </p>

          <h2 style={{ color: '#fff', fontSize: '20px', marginTop: '32px', marginBottom: '16px' }}>Advertising Disclaimer</h2>
          <p>
            VIBEMENOW is a free service supported by advertising, including ads served by Google AdSense. The advertisements displayed on this website are provided by third-party advertisers. VIBEMENOW does not endorse or guarantee the products or services advertised. Any transactions that occur between you and the advertisers are solely between you and the advertiser. We are not responsible for any loss or damage of any kind incurred as a result of any such dealings.
          </p>

          <h2 style={{ color: '#fff', fontSize: '20px', marginTop: '32px', marginBottom: '16px' }}>Fair Use & Copyright</h2>
          <p>
            Some content on VIBEMENOW, including game descriptions, trivia questions, and educational articles, may reference copyrighted works such as movies, songs, or brands for the purpose of commentary, criticism, education, or parody. Such use is believed to constitute "fair use" under applicable copyright laws. VIBEMENOW does not claim ownership of any third-party trademarks or copyrighted materials referenced in its content.
          </p>

          <div style={{ marginTop: '40px', borderTop: '1px solid #1a1a2e', paddingTop: '20px', color: '#555' }}>
            For any questions regarding this disclaimer, please reach out via our <Link href="/contact" style={{ color: '#ffe600', textDecoration: 'underline' }}>Contact Form</Link>.
          </div>
        </div>
      </div>
    </div>
  );
}
